application: arunjit-test
version: notes-dev-1
runtime: go
api_version: go1

handlers:
- url: /rpc
  script: _go_app

- url: /.+
  static_dir: www

- url: /
  static_files: www/index.html
  upload: www/index.html
